# Generated by Django 3.0.1 on 2019-12-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('comentarios', models.TextField()),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/propriedades/')),
                ('tags', models.CharField(max_length=200)),
                ('tipo_multipropriedade', models.CharField(choices=[('IM', 'Imóvel'), ('VE', 'Veículo')], max_length=2)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('multiproprietarios', models.ManyToManyField(to='base.User')),
            ],
            options={
                'verbose_name_plural': 'Propriedades',
            },
        ),
    ]
