# Generated by Django 3.0.2 on 2020-01-03 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMultiPropriedade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('nome', models.CharField(max_length=32, unique=True)),
                ('descricao', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Multipropriedade',
                'verbose_name_plural': 'Tipos de Multipropriedades',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('comentarios', models.TextField()),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/propriedades/')),
                ('tags', models.CharField(max_length=200)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('multiproprietarios', models.ManyToManyField(to='base.User')),
                ('tipo_multipropriedade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propriedades.TipoMultiPropriedade')),
            ],
            options={
                'verbose_name_plural': 'Propriedades',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
